// This is an autogenerated header file for the library afgclib
#ifndef AFGCLIB_H
#define AFGCLIB_H

// Add your library code here

void print_hello_world(void);

// Add your library code here

int add_two_numbers(int a, int b);

#endif // AFGCLIB_H
