// This is an autogenerated header file for the library afgclib
#ifndef AFGCLIB_H
#define AFGCLIB_H

/// prints hello world
void print_hello_world(void);

/// adds two numbers
int add_two_numbers(int a, int b);

#endif // AFGCLIB_H
